[font]
normal = { family = "Hack" }
size = 13.0

# Originally from https://github.com/aaron-williamson/base16-alacritty
[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.bright]
black = "0x585858"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xf8f8f8"
yellow = "0xf7ca88"

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[colors.search.focused_match]
background = "0xf7ca88"
foreground = "0x181818"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"
